[project]
name = "vigmykd-api"
version = "0.1.0"
description = "REST API for vigmykd"
authors = [
    { name = "discocat", email = "vigmykd@runderscore.com" }
]
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.136.1"
]

license = { file = "LICENSE" }

[project.optional-dependencies]
dev = [
    "flake8>=6.0",
    "mypy>=1.0",
    "pytest>=9.0.2"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"